# Generated by Django 5.0.7 on 2024-07-30 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursosapp', '0002_remove_curso_estudiantes_remove_curso_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
